# Generated by Django 5.1.6 on 2025-09-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0003_feedbackdata_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='object_id',
            field=models.CharField(max_length=255, verbose_name='Object ID'),
        ),
    ]
