# Generated by Django 5.1.6 on 2025-09-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0004_alter_feedbackdata_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackdata',
            name='field',
            field=models.CharField(blank=True, help_text='The specific field of the object the feedback is about', max_length=255, null=True, verbose_name='Field'),
        ),
    ]
