# Generated by Django 5.2.9 on 2026-03-12 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0005_feedbackdata_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackdata',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date updated'),
        ),
    ]
