# Generated by Django 5.1.6 on 2025-06-08 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                        ],
                        help_text="The type of event this configuration applies to (e.g., 'create', 'update', 'delete').",
                        max_length=100,
                    ),
                ),
                (
                    "send_to_admin",
                    models.BooleanField(
                        default=True,
                        help_text="Whether to send notifications to the admin.",
                    ),
                ),
                (
                    "send_to_user",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send notifications to the user.",
                    ),
                ),
                (
                    "send_to_group_user",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to send notifications to group users.",
                    ),
                ),
                (
                    "group_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Groups of users to send notifications to.",
                        related_name="notification_configs",
                        to="auth.group",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text="The model this configuration applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_configs",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific users to send notifications to.",
                        related_name="notification_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
