# Generated by Django 5.1.6 on 2025-06-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationconfig",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                ],
                help_text="The type of event this configuration applies to (e.g., 'create', 'update', 'delete').",
                max_length=100,
            ),
        ),
    ]
