# Generated by Django 5.1.6 on 2025-06-09 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_alter_notificationconfig_event_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("obj_link", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False, verbose_name="Read")),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("info", "info"),
                            ("success", "success"),
                            ("warning", "warning"),
                            ("danger", "danger"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("update", "update"),
                            ("create", "create"),
                            ("restore", "restore"),
                            ("delete", "delete"),
                        ],
                        max_length=25,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "verbose_name_plural": "notifications",
                "db_table": "notifications",
            },
        ),
    ]
