# Generated by Django 5.1.6 on 2025-06-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="flag",
            field=models.CharField(
                choices=[
                    ("info", "info"),
                    ("success", "success"),
                    ("warning", "warning"),
                    ("error", "error"),
                    ("danger", "danger"),
                ],
                max_length=25,
            ),
        ),
    ]
