# Generated by Django 5.1.6 on 2025-07-21 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0004_alter_notification_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="keywords",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
