# Generated by Django 5.1.6 on 2025-07-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0005_notification_keywords"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="keywords",
        ),
    ]
