# Generated by Django 5.1.6 on 2025-07-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0006_remove_notification_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="changed_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Changed Data"),
        ),
    ]
