# Generated by Django 5.1.6 on 2025-07-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0007_notification_changed_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="changed_data",
            field=models.TextField(blank=True, null=True, verbose_name="Changed Data"),
        ),
    ]
