# Generated by Django 5.2.10 on 2026-03-28 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notification', '0011_alter_notification_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(blank=True, choices=[('update', 'update'), ('create', 'create'), ('restore', 'restore'), ('delete', 'delete')], max_length=25, null=True, verbose_name='Action Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='flag',
            field=models.CharField(choices=[('info', 'info'), ('success', 'success'), ('warning', 'warning'), ('error', 'error'), ('danger', 'danger')], max_length=25, verbose_name='Notification Type'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='obj_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Object Link'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='event_type',
            field=models.CharField(choices=[('all', 'All'), ('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], help_text="The type of event this configuration applies to (e.g., 'create', 'update', 'delete').", max_length=100, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='group_users',
            field=models.ManyToManyField(blank=True, help_text='Groups of users to send notifications to.', related_name='notification_configs', to='auth.group', verbose_name='Group Users'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='model',
            field=models.ForeignKey(help_text='The model this configuration applies to.', on_delete=django.db.models.deletion.CASCADE, related_name='notification_configs', to='contenttypes.contenttype', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='send_to_admin',
            field=models.BooleanField(default=True, help_text='Whether to send notifications to the admin.', verbose_name='Send to Admin'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='send_to_group_user',
            field=models.BooleanField(default=False, help_text='Whether to send notifications to group users.', verbose_name='Send to Group Users'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='send_to_user',
            field=models.BooleanField(default=False, help_text='Whether to send notifications to the user.', verbose_name='Send to User'),
        ),
        migrations.AlterField(
            model_name='notificationconfig',
            name='users',
            field=models.ManyToManyField(blank=True, help_text='Specific users to send notifications to.', related_name='notification_configs', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
