# Generated by Django 5.2.9 on 2026-03-12 10:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_alter_excelfile_options_alter_pdffile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date updated'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date updated'),
        ),
    ]
