# Generated by Django 5.2.13 on 2026-04-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_alter_excelfile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash'),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash'),
        ),
    ]
