# Generated by Django 5.2.14 on 2026-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0004_excelfile_hash_pdffile_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelfile',
            name='file',
            field=models.FileField(upload_to='excels', verbose_name='Excel File'),
        ),
        migrations.AlterField(
            model_name='excelfile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='file',
            field=models.FileField(upload_to='pdfs', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='pdffile',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
