# Generated by Django 6.0.6 on 2026-07-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0005_alter_excelfile_file_alter_excelfile_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, only authorized users/groups can access this file.', verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='is_public',
            field=models.BooleanField(default=True, help_text='If unchecked, only authorized users/groups can access this file.', verbose_name='Public'),
        ),
    ]
