# Generated by Django 6.0.6 on 2026-07-15 05:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0006_excelfile_is_public_pdffile_is_public'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HTMLFile',
            fields=[
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date created')),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date updated')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='done', max_length=25, verbose_name='Status')),
                ('method', models.CharField(choices=[('upload', 'Upload'), ('auto', 'Auto')], default='upload', max_length=25, verbose_name='Method')),
                ('hash', models.CharField(blank=True, max_length=64, null=True, verbose_name='Hash')),
                ('is_public', models.BooleanField(default=True, help_text='If unchecked, only authorized users/groups can access this file.', verbose_name='Public')),
                ('file', models.FileField(upload_to='htmls', verbose_name='HTML File')),
                ('created_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('updated_by', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'HTML File',
                'verbose_name_plural': 'HTML Files',
            },
        ),
    ]
