# Generated by Django 6.0.6 on 2026-07-15 06:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('file_management', '0007_htmlfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfile',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_allowed_groups', to='auth.group', verbose_name='Allowed Groups'),
        ),
        migrations.AddField(
            model_name='excelfile',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_allowed_users', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users'),
        ),
        migrations.AddField(
            model_name='htmlfile',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_allowed_groups', to='auth.group', verbose_name='Allowed Groups'),
        ),
        migrations.AddField(
            model_name='htmlfile',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_allowed_users', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users'),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_allowed_groups', to='auth.group', verbose_name='Allowed Groups'),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='%(class)s_allowed_users', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users'),
        ),
    ]
