# Generated by Django 5.1.6 on 2025-05-28 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_imagemodel_userprofile_user_avatar_user_biography_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="obj_link",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
