# Generated by Django 5.1.6 on 2025-06-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_notification_obj_link"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
