# Generated by Django 5.1.6 on 2025-08-21 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_softdelete',
            field=models.BooleanField(default=False, help_text='Show soft deleted items in the list view', verbose_name='show soft delete'),
        ),
    ]
