# Generated by Django 5.1.6 on 2025-09-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_show_softdelete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_bot',
            field=models.BooleanField(default=False, help_text='Designate whether the user is a bot account', verbose_name='is bot'),
        ),
    ]
