# Generated by Django 5.1.6 on 2025-11-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_is_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='App name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('icon', models.CharField(blank=True, help_text='Icon name (Material Symbols Outlined) or URL', max_length=255, null=True, verbose_name='Icon')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'App',
                'verbose_name_plural': 'Apps',
                'db_table': 'apps',
            },
        ),
    ]
