# Generated by Django 5.1.6 on 2025-11-03 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_app_created_at_app_created_by_app_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='app',
            table=None,
        ),
    ]
