# Generated by Django 5.1.6 on 2025-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_app_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category'),
        ),
    ]
