# Generated by Django 5.1.6 on 2025-11-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_app_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='app',
            options={'ordering': ['id'], 'verbose_name': 'App', 'verbose_name_plural': 'Apps'},
        ),
    ]
