# Generated by Django 5.1.6 on 2025-11-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_app_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='permission',
            field=models.CharField(blank=True, help_text='Permission required to access this app', max_length=255, null=True, verbose_name='Permission'),
        ),
    ]
