# Generated by Django 5.1.6 on 2025-11-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_app_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True, verbose_name='Thumbnail URL'),
        ),
    ]
