# Generated by Django 5.2.10 on 2026-03-29 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_app_created_at_alter_app_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, help_text='Single IPv4 or IPv6 address. Use IP_BLACKLIST in .env for CIDR ranges.', unique=True, verbose_name='IP address')),
                ('reason', models.CharField(blank=True, max_length=500, verbose_name='reason')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Leave empty for permanent block. Temporary blocks expire automatically via Redis TTL.', null=True, verbose_name='blocked until')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_blacklists', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'IP blacklist',
                'verbose_name_plural': 'IP blacklists',
                'db_table': 'ip_blacklists',
                'ordering': ['-created_at'],
            },
        ),
    ]
