# Generated by Django 5.2.10 on 2026-03-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_uablacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uablacklist',
            name='pattern',
            field=models.CharField(help_text="Substring or regex to match against the User-Agent header. E.g. 'GPTBot', 'https://openai.com'.", max_length=500, unique=True, verbose_name='pattern'),
        ),
    ]
