# Generated by Django 5.2.13 on 2026-04-27 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_user_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP address')),
                ('user_agent', models.TextField(verbose_name='User agent')),
                ('first_seen', models.DateTimeField(auto_now_add=True, verbose_name='First seen')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Last seen')),
            ],
            options={
                'verbose_name': 'visit profile',
                'verbose_name_plural': 'visit profiles',
                'db_table': 'visit_profiles',
                'indexes': [models.Index(fields=['ip_address'], name='visit_profi_ip_addr_286b2b_idx'), models.Index(fields=['first_seen'], name='visit_profi_first_s_52b849_idx')],
                'unique_together': {('ip_address', 'user_agent')},
            },
        ),
        migrations.AddField(
            model_name='useractivity',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.visitprofile'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['profile', 'timestamp'], name='user_activi_profile_96be77_idx'),
        ),
    ]
