# Generated by Django 5.2.13 on 2026-04-27 08:22

from django.db import migrations


def create_visit_profiles_from_existing_data(apps, schema_editor):
    """Tạo VisitProfile từ dữ liệu ip_address/user_agent của UserActivity."""
    UserActivity = apps.get_model('base', 'UserActivity')
    VisitProfile = apps.get_model('base', 'VisitProfile')

    # Group by (ip_address, user_agent) — mỗi combo tạo 1 profile
    key_to_first_activity = {}
    
    for activity in UserActivity.objects.all():
        if activity.ip_address:
            key = (activity.ip_address, (activity.user_agent or '')[:500])
            if key not in key_to_first_activity:
                key_to_first_activity[key] = activity

    # Bulk create VisitProfiles (1 profile per unique IP+UA combo)
    profiles_to_create = [
        VisitProfile(ip_address=ip, user_agent=ua[:500])
        for ip, ua in key_to_first_activity.keys()
    ]
    VisitProfile.objects.bulk_create(profiles_to_create)

    # Build lookup: (ip, ua) → profile_id
    ua_lookup = {(p.ip_address, p.user_agent): p.id for p in profiles_to_create}

    # Update UserActivity.profile
    batch_size = 1000
    activities_to_update = []
    
    for activity in UserActivity.objects.all():
        if activity.ip_address:
            key = (activity.ip_address, (activity.user_agent or '')[:500])
            if key in ua_lookup:
                activity.profile_id = ua_lookup[key]
        
        if activity.profile_id is not None:
            activities_to_update.append(activity)

        if len(activities_to_update) >= batch_size:
            UserActivity.objects.bulk_update(activities_to_update, ['profile_id'])
            activities_to_update.clear()
    
    if activities_to_update:
        UserActivity.objects.bulk_update(activities_to_update, ['profile_id'])


def reverse_create_visit_profiles(apps, schema_editor):
    """Reverse migration — không cần làm gì."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_add_visit_profile_and_fk_fields'),
    ]

    operations = [
        migrations.RunPython(create_visit_profiles_from_existing_data, reverse_create_visit_profiles),
    ]
