# Generated by Django 5.2.13 on 2026-04-27 08:25

from django.db import migrations


def remove_duplicate_visit_profiles(apps, schema_editor):
    """Xóa duplicate VisitProfiles và update UserActivity.profile references."""
    UserActivity = apps.get_model('base', 'UserActivity')
    VisitProfile = apps.get_model('base', 'VisitProfile')

    # Find all unique (ip_address, user_agent) pairs and keep the first profile for each
    profiles_by_key = {}
    
    for profile in VisitProfile.objects.all():
        key = (profile.ip_address, profile.user_agent or '')
        if key not in profiles_by_key:
            profiles_by_key[key] = profile.id
    
    # Build lookup: old_profile_id → kept_profile_id
    id_mapping = {}
    for profile in VisitProfile.objects.all():
        key = (profile.ip_address, profile.user_agent or '')
        id_mapping[profile.id] = profiles_by_key[key]

    # Update UserActivity.profile to point to the correct profile_id
    batch_size = 1000
    activities_to_update = []
    
    for activity in UserActivity.objects.all():
        if activity.profile_id and activity.profile_id in id_mapping:
            new_profile_id = id_mapping[activity.profile_id]
            if new_profile_id != activity.profile_id:
                activity.profile_id = new_profile_id
                activities_to_update.append(activity)
        
        if len(activities_to_update) >= batch_size:
            UserActivity.objects.bulk_update(activities_to_update, ['profile_id'])
            activities_to_update.clear()
    
    if activities_to_update:
        UserActivity.objects.bulk_update(activities_to_update, ['profile_id'])

    # Delete duplicate profiles (keep only one per unique key)
    kept_ids = set(profiles_by_key.values())
    VisitProfile.objects.exclude(pk__in=kept_ids).delete()


def reverse_remove_duplicates(apps, schema_editor):
    """Reverse migration — không cần làm gì."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_populate_visit_profiles'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_visit_profiles, reverse_remove_duplicates),
    ]
