# Generated by Django 5.2.13 on 2026-04-27 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_remove_duplicate_visit_profiles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='useractivity',
            name='user_agent',
        ),
        migrations.CreateModel(
            name='AnonymousActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='Path')),
                ('method', models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST')], max_length=10, null=True, verbose_name='Method')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('status_code', models.IntegerField(blank=True, null=True, verbose_name='Status code')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('timelapse', models.DurationField(blank=True, null=True, verbose_name='Timelapse')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.visitprofile')),
            ],
            options={
                'verbose_name': 'anonymous activity',
                'verbose_name_plural': 'anonymous activities',
                'db_table': 'anonymous_activities',
                'indexes': [models.Index(fields=['profile', 'timestamp'], name='anonymous_a_profile_3644ec_idx')],
            },
        ),
    ]
