# Generated by Django 5.2.13 on 2026-04-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_remove_useractivity_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitprofile',
            name='user_agent',
            field=models.CharField(max_length=500, verbose_name='User agent'),
        ),
    ]
