# Generated by Django 5.2.13 on 2026-04-27 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_visitprofile_user_agent_to_charfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonymousactivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'anonymous activity', 'verbose_name_plural': 'anonymous activities'},
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp'], 'verbose_name': 'user activity', 'verbose_name_plural': 'user activities'},
        ),
    ]
