# Generated by Django 5.2.13 on 2026-04-27 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_anonymousactivity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousactivity',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymousactivities', to='base.visitprofile'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='useractivities', to='base.visitprofile'),
        ),
    ]
