# Generated by Django 5.2.14 on 2026-05-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_anonymousactivity_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymousactivity',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10, null=True, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('HEAD', 'HEAD'), ('OPTIONS', 'OPTIONS')], max_length=10, null=True, verbose_name='Method'),
        ),
    ]
