# Generated by Django 6.0.6 on 2026-07-30 10:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_add_email_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='subject',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date created'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Date updated'),
        ),
    ]
